name: psi-eci-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # basic libraries
  - numpy
  - pandas
  - scipy

  # graphs
  - matplotlib
  - seaborn

  # econometrics
  - statsmodels

  # notebooks
  - jupyter
  - jupyterlab

  # visualization and panels
  - altair

  # streamlit
  - streamlit

  # additional packages via pip
  - pip:
      - linearmodels
      - plotnine
